### ISSUE TITLE
PRACTICA 4 MODELO DE NEGOCIO 

### ISSUE THREAD

**Issue by IrvinSanchez-dev** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-en-web-3-0-dinamita#1]
[REPORTE DE PRACTICA MODELO DE NEGOCIOS.pdf](https://github.com/user-attachments/files/17122039/REPORTE.DE.PRACTICA.MODELO.DE.NEGOCIOS.pdf)
EQUIPO:
Diego Cruz Cruz
Marco Uriel Rosas Garcia
Irvin Jimenez Sanchez

**Comment by Kevinosorio77** [comment]
Realizando la evaluación cumple con los requisititos de la rubrica por lo que el valor es de 20%

**Comment by josealfredo79** [comment]
bien hecho y revisado..
